"""Pydantic schemas for AI-powered language games."""
from __future__ import annotations

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Generation request (shared)
# ---------------------------------------------------------------------------

class GameGenerateIn(BaseModel):
    """Common request body for any game-generation endpoint.

    If `topic` is None/empty, the backend pulls items from the user's
    vocabulary database at their current CEFR level (default mode).
    If `topic` is provided, content is generated by the LLM around that topic.
    """

    topic: str | None = Field(default=None, max_length=200)
    language: str = Field(default="en", min_length=2, max_length=8)
    count: int = Field(default=8, ge=1, le=20)
    level: str | None = Field(
        default=None,
        description="CEFR level override (A1..C2). Defaults to user's level.",
    )
    translation_lang: str | None = Field(
        default=None,
        min_length=2,
        max_length=8,
        description="Native translation language override (e.g. 'ru' or 'kk').",
    )


# ---------------------------------------------------------------------------
# Word Match
# ---------------------------------------------------------------------------

class WordPair(BaseModel):
    word: str
    translation: str


class WordMatchOut(BaseModel):
    topic_label: str | None = None
    level: str
    pairs: list[WordPair]


# ---------------------------------------------------------------------------
# Word Scramble
# ---------------------------------------------------------------------------

class ScrambleItem(BaseModel):
    word: str
    translation: str
    hint: str | None = None


class WordScrambleOut(BaseModel):
    topic_label: str | None = None
    level: str
    items: list[ScrambleItem]


# ---------------------------------------------------------------------------
# Sentence Builder
# ---------------------------------------------------------------------------

class SentenceItem(BaseModel):
    sentence: str
    translation: str


class SentenceBuilderOut(BaseModel):
    topic_label: str | None = None
    level: str
    items: list[SentenceItem]


# ---------------------------------------------------------------------------
# Hangman
# ---------------------------------------------------------------------------

class HangmanOut(BaseModel):
    topic_label: str | None = None
    level: str
    word: str
    translation: str
    hint: str
